### ISSUE TITLE
Implement Global Shutdown Action

### ISSUE THREAD

**Issue by Twonki** [Twonki/Solaris#87]
The Current "Quit" Action just kills the Program (System.exit(0))

We want a quit function which is a little smarter - saving the current configuration and calling applications "stop()" method. 

ToDo:

- [ ] Access the config in a static way
- [ ] Create a static method for shut down
- [ ] Create an Action calling it//Rewrite Quit Action

Please make it quite modular - if we add #18 we would like to save our galaxy to a file aswell. 
Maybe we want to save player statistics somewhere.

**Comment by DeusVultSVK** [comment]
can i grab this issue?

**Comment by Twonki** [comment]
@DeusVultSVK  Sure go ahead!

**Comment by Twonki** [comment]
@DeusVultSVK dont forget to assign yourself 💯
