### ISSUE TITLE
Distant Galaxy builds Stars with Wrong name 

### ISSUE THREAD

**Issue by Twonki** [Twonki/Solaris#95]
**Describe the bug**
Stars are numbered wrong - when one disappears and the next spawns its usually numbered 249 or 248,  not like a running number. 
**To Reproduce**

Start the Game and view the logfile in debug 
(Both master and dev)

**Expected behavior**
The when 250 stars are build, the following new start should be numbered 251 etc.

**Comment by b0n541** [comment]
I would take this one.
